---
title: "주식 거래량과 거시데이터"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = F, warning = F)
```

## 데이터 소개

kospi: 코스피 거래대금
kosdaq: 코스피 거래대금
ex_rate: 원/달러 환율(월평균)
bond_trading_volume: 채권 거래대금
base_money: 본원통화(평잔)
m1: m1 통화량(평잔)
m2: m2 통화량(평잔)
total_bank_loan: 예금은행 대출금(평잔)


```{r data loading}
# 데이터 불러오기
data = read.csv('data_r.csv', header = T, stringsAsFactors = F)

# 패키지 로딩
pkg = c( 'stringr', 'dplyr', 'ggplot2', 'plotly', 'magrittr', 'corrplot', 'tidyr')

new.pkg = pkg[!(pkg %in% installed.packages()[, "Package"])]

if (length(new.pkg)) 
  install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)

```


```{r correlation}
# 상관관계 도표(수준 변수에 대하여)
cor(data[, 2:9]) %>% corrplot(method = 'color', type = 'upper',
                             addCoef.col = 'black', number.cex = 0.7,
                             tl.cex = 0.6, tl.srt = 45, tl.col = 'black',
                             col = colorRampPalette(c('blue', 'white', 'red'))(200),
                             mar = c(0, 0, 0.5, 0))

# 상관관계 도표(변화율 변수에 대하여)
cor(data[-1, 10:17]) %>% corrplot(method = 'color', type = 'upper',
                              addCoef.col = 'black', number.cex = 0.7,
                              tl.cex = 0.6, tl.srt = 45, tl.col = 'black',
                              col = colorRampPalette(c('blue', 'white', 'red'))(200),
                              mar = c(0, 0, 0.5, 0))

```

```{r test}
# 상관관계가 유의한지 test

# 코스피 거래량과 환율
cor.test(data[, 2], data[, 4])

# 코스피 거래량과 채권 거래량
cor.test(data[, 2], data[, 4])

# 코스피 거래량과 본원통화량
cor.test(data[, 2], data[, 4])

# 코스피 거래량 월별 변화율과 환율 변화율
cor.test(data[, 10], data[, 12])

# 코스피 거래량 월별 변화율과 채권거래량 변화율
cor.test(data[, 10], data[, 13])

```